import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Blog App-multi-zones</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1>Welcome to our blog!</h1>
          <p>
            Welcome to the blog section of our website, which is powered by a
            separate micro frontend built using Next.js zones. Our blog section
            is an excellent example of how zones can help you manage complex
            projects and optimize performance.
          </p>

          <p>
            By separating the blog from the rest of the website, we can apply
            unique configurations and functionality that are specific to the
            blog. For example, we can configure caching and routing to optimize
            page load times and SEO, as well as apply custom authentication and
            authorization rules to ensure that only authorized users can access
            certain content.
          </p>

          <p>
            Using a separate micro frontend also allows us to scale our blog
            independently of the rest of the website. If we experience a spike
            in traffic on our blog, we can allocate more resources to the blog
            micro frontend without affecting the rest of the websites
            performance.
          </p>

          <p>
            We haveve designed our blog section to be easy to navigate and
            search, with intuitive categories and tags, as well as a powerful
            search function. We have also included a commenting system that
            allows readers to engage with each other and share their thoughts on
            our posts.
          </p>
          <p>
            Whether you are a casual reader or a dedicated blogger, we hope that
            you will find our blog section to be a valuable resource. Thank you
            for visiting our site, and happy reading!
          </p>
          <h2>Some blog posts</h2>
          <ol>
            <li>
              <Link href="/post-1">
                Post 1: How to Build a Next.js App from Scratch
              </Link>
            </li>
          </ol>

          <a href="/">Go back home</a>
        </div>
      </main>
    </>
  );
}
